name: Build & Deploy Sphinx docs to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'src/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install doc deps
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-book-theme sphinx-autodoc-typehints

      - name: Generate API stubs
        run: sphinx-apidoc -o docs/source/api src/cardiology_gen_ai --force --module-first

      - name: Build Sphinx HTML
        env:
          SPHINX_BUILD: "1"
        run: |
          test -d docs/source/conf.py || (echo "Missing docs/ directory" && exit 2)
          sphinx-build -b html docs docs/build/html
          touch docs/build/html/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
